FROM python:3.12-slim
WORKDIR /app
COPY backend/ backend/
COPY config /app/config
RUN pip install -e "backend/"
RUN python -m spacy download en_core_web_sm
CMD ["uvicorn", "backend.infrastructure.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
